### ISSUE TITLE
Research DITAP Brand

### ISSUE THREAD

**Issue by kellysmith1008** [usds/ditap-curriculum-update#89]
**Dependencies**
- none

**Tasks**
- [ ] Review DITAP deliverables and training materials to document consistent patterns
- [ ] Discover inconsistent patterns and document them
- [ ] Compare existing patterns with industry standards and 508 compliance
- [ ] Document missing patterns (colors, font size, references, etc)
- [ ] Share findings and suggestions with Frank McNally

**Definition of success**
- [ ] DITAP deliverables have been reviewed 
- [ ] Consistent and inconsistent patterns have been documented
- [ ] Missing patterns have been documented
- [ ] Findings and suggestions have been shared

**Other information**

- Reach out to Frank/USDS about what they already have for this?
- Vendors have asked for this in the past?
- There has been no consistent DITAP brand in the past (to our knowledge). 

- A follow-up ticket to create the brand will be necessary - this is solely to research and document the existing brand and what needs to be created

**Comment by kellysmith1008** [comment]
[Document used for brand discovery](https://docs.google.com/document/d/1dzodHvFW_iIH2PxSttrPw60lPr12Loshno1w4puo3Co/edit?tab=t.0)
